## src/Function/BUILD

cc_library(
    name = "Function",
    srcs = ["Function.cpp"],
    hdrs = ["Function.hpp"],
    data = [
        "Fio.txt",
        "Groups.txt",
        "Students.txt",
    ],
    visibility = ["//visibility:public"],
)
