## src/tests/FunctionsTests/BUILD

cc_library(
    name = "FunctionsTests",
    srcs = ["FunctionsTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Functions:Functions",
    ]
)
