## src/tests/AuthorTests/BUILD

cc_library(
    name = "AuthorTests",
    srcs = ["AuthorTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Author:Author",
    ]
)
