## src/tests/myStringTests/BUILD

cc_library(
    name = "myStringTests",
    srcs = ["myStringTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/myString:myString",
    ]
)
