## src/tests/BusTrackTests/BUILD

cc_library(
    name = "BusTrackTests",
    srcs = ["BusTrackTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/BusTrack:BusTrack",
    ]
)
