## src/Tree/BUILD

cc_library(
    name = "Tree",
    srcs = ["Tree.cpp", "FruitTree.cpp", "ForestTree.cpp"],
    hdrs = ["Tree.hpp", "FruitTree.hpp", "ForestTree.hpp"],
    visibility = ["//visibility:public"],
)
