## src/Student/BUILD

cc_library(
    name = "Student",
    srcs = ["Student.cpp","StudentAfterFirstSession.cpp", "StudentAfterSecondSession.cpp"],
    hdrs = ["Student.hpp","StudentAfterFirstSession.hpp", "StudentAfterSecondSession.hpp"],
    visibility = ["//visibility:public"],
)
