## src/BusTrackVector/BUILD

cc_library(
    name = "BusTrackVector",
    srcs = ["BusTrackVector.cpp"],
    hdrs = ["BusTrackVector.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/BusTrack:BusTrack",
    ],
)
