## src/Functions/BUILD

cc_library(
    name = "Functions",
    srcs = ["Functions.cpp"],
    hdrs = ["Functions.hpp"],
    deps = ["//src/Student:Student"],
    visibility = ["//visibility:public"],
)
