## src/tests/TDequeTests/BUILD

cc_library(
    name = "TDequeTests",
    srcs = ["TDequeTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/TDeque:TDeque",
    ]
)