## src/tests/ProductTests/BUILD

cc_library(
    name = "ProductTests",
    srcs = ["ProductTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Product:Product",
    ]
)
