## src/tests/BookTests/BUILD

cc_library(
    name = "BookTests",
    srcs = ["BookTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Book:Book",
    ]
)
