## src/tests/FunctionTests/BUILD

cc_library(
    name = "FunctionTests",
    srcs = ["FunctionTests.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@googletest//:gtest_main",
        "//src/Function:Function",
    ]
)
