## src/AuthorList/BUILD

cc_library(
    name = "AuthorList",
    srcs = ["AuthorList.cpp"],
    hdrs = ["AuthorList.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/Author:Author",
    ],
)
