## src/TreeContainer/BUILD

cc_library(
    name = "TreeContainer",
    srcs = ["TreeContainer.cpp"],
    hdrs = ["TreeContainer.hpp"],
    deps = [
        
        "//src/Tree:Tree",
    ],
    visibility = ["//visibility:public"],
)
